default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["host"] %>
  port: <%= ENV["port"] %>
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development_tibuTicket
  
test:
  <<: *default
  database: backend_test_tibuTicket

production:
  <<: *default
  database: backend_production_tibuTicket